### Create user

POST http://localhost:3000/user
Content-Type:application/json
Fake-Header: Tamer
Foo:bar

{
	"foo": "bar"
}


### Read user


// some comment, because whatever
GET http://foobar/user HTTP/1.1


// more comments

### Some other
POST http://foo/bar HTTP/1.1